# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CelticMajora
masthead_title: Home
name: "Caleb Donoho"
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm CelticMajora, and I'll be using this site to talk about projects I'm 
  working on, hobbies I pursue, and other random topics. Outside of posts talking 
  about what I do, I'll also just use this as a hub linking out things I do.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.celticmajora.com"
twitter:
  username: "CelticMajora"
social:
  links:
    - "https://twitter.com/CelticMajora"
    - "https://www.linkedin.com/in/caleb-donoho-1b8681135"
author:
  name: "Caleb Donoho"
  avatar: "/assets/images/author_image.jpg"
  bio: "NYC based engineer currently working in Flutter with a passion for Software Quality Assurance"
  location: "Queens, NY"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CelticMajora"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/CelticMajora"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CelticMajora"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/CelticMajora"
repository: "CelticMajora/CelticMajora.github.io"
search: true
paginate: 5
teaser: /assets/images/fallback_teaser.jpg

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      layout: single
      share: true
      related: true
      author_profile: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
